export const groups = [
  { name: "Gruppo A", teams: ["🇲🇽 Mexico", "🇿🇦 South Africa", "🇰🇷 South Korea", "🇨🇿 Czechia"] },
  { name: "Gruppo B", teams: ["🇨🇦 Canada", "🇧🇦 Bosnia and Herzegovina", "🇶🇦 Qatar", "🇨🇭 Switzerland"] },
  { name: "Gruppo C", teams: ["🇧🇷 Brazil", "🇭🇹 Haiti", "🇲🇦 Morocco", "🏴 Scotland"] },
  { name: "Gruppo D", teams: ["🇺🇸 United States", "🇦🇺 Australia", "🇵🇾 Paraguay", "🇹🇷 Türkiye"] },
  { name: "Gruppo E", teams: ["🇨🇼 Curaçao", "🇪🇨 Ecuador", "🇩🇪 Germany", "🇨🇮 Ivory Coast"] },
  { name: "Gruppo F", teams: ["🇳🇱 Netherlands", "🇯🇵 Japan", "🇸🇪 Sweden", "🇹🇳 Tunisia"] },
  { name: "Gruppo G", teams: ["🇧🇪 Belgium", "🇪🇬 Egypt", "🇮🇷 Iran", "🇳🇿 New Zealand"] },
  { name: "Gruppo H", teams: ["🇨🇻 Cape Verde", "🇸🇦 Saudi Arabia", "🇪🇸 Spain", "🇺🇾 Uruguay"] },
  { name: "Gruppo I", teams: ["🇫🇷 France", "🇳🇴 Norway", "🇸🇳 Senegal", "🇮🇶 Iraq"] },
  { name: "Gruppo J", teams: ["🇦🇷 Argentina", "🇩🇿 Algeria", "🇦🇹 Austria", "🇯🇴 Jordan"] },
  { name: "Gruppo K", teams: ["🇵🇹 Portugal", "🇨🇩 DR Congo", "🇨🇴 Colombia", "🇺🇿 Uzbekistan"] },
  { name: "Gruppo L", teams: ["🏴 England", "🇭🇷 Croatia", "🇬🇭 Ghana", "🇵🇦 Panama"] },
];

const startDate = new Date("2026-06-11T21:00:00");

export const matches = groups.flatMap((group, groupIndex) => {
  const [t1, t2, t3, t4] = group.teams;
  const base = groupIndex * 6;
  const dayOffset = groupIndex;
  const d1 = new Date(startDate); d1.setDate(startDate.getDate() + dayOffset);
  const d2 = new Date(startDate); d2.setDate(startDate.getDate() + dayOffset + 5);
  const d3 = new Date(startDate); d3.setDate(startDate.getDate() + dayOffset + 10);
  const iso = (d, h) => { const x = new Date(d); x.setHours(h,0,0,0); return x.toISOString(); };
  return [
    { id: `m${base + 1}`, group: group.name, date: "Da definire", kickoff: iso(d1, 18), home: t1, away: t2 },
    { id: `m${base + 2}`, group: group.name, date: "Da definire", kickoff: iso(d1, 21), home: t3, away: t4 },
    { id: `m${base + 3}`, group: group.name, date: "Da definire", kickoff: iso(d2, 18), home: t1, away: t3 },
    { id: `m${base + 4}`, group: group.name, date: "Da definire", kickoff: iso(d2, 21), home: t4, away: t2 },
    { id: `m${base + 5}`, group: group.name, date: "Da definire", kickoff: iso(d3, 18), home: t4, away: t1 },
    { id: `m${base + 6}`, group: group.name, date: "Da definire", kickoff: iso(d3, 21), home: t2, away: t3 },
  ];
});

export const knockoutRounds = [
  { round: "Sedicesimi", matches: ["1A - Migliore 3ª", "1B - Migliore 3ª", "1C - Migliore 3ª", "1D - Migliore 3ª", "1E - 2F", "1F - 2E", "1G - 2H", "1H - 2G", "1I - 2J", "1J - 2I", "1K - 2L", "1L - 2K", "2A - 2B", "2C - 2D", "2E - 2F", "2G - 2H"] },
  { round: "Ottavi", matches: ["Vincente S1 - Vincente S2", "Vincente S3 - Vincente S4", "Vincente S5 - Vincente S6", "Vincente S7 - Vincente S8", "Vincente S9 - Vincente S10", "Vincente S11 - Vincente S12", "Vincente S13 - Vincente S14", "Vincente S15 - Vincente S16"] },
  { round: "Quarti", matches: ["Vincente O1 - Vincente O2", "Vincente O3 - Vincente O4", "Vincente O5 - Vincente O6", "Vincente O7 - Vincente O8"] },
  { round: "Semifinali", matches: ["Vincente Q1 - Vincente Q2", "Vincente Q3 - Vincente Q4"] },
  { round: "Finale 3° posto", matches: ["Perdente SF1 - Perdente SF2"] },
  { round: "Finale", matches: ["Vincente SF1 - Vincente SF2"] },
];

export const topScorers = [
  "🇲🇽 Santiago Giménez (Mexico)",
  "🇲🇽 Raúl Jiménez (Mexico)",
  "🇲🇽 Hirving Lozano (Mexico)",
  "🇲🇽 Henry Martín (Mexico)",
  "🇲🇽 Uriel Antuna (Mexico)",
  "🇲🇽 Julián Quiñones (Mexico)",
  "🇲🇽 Roberto Alvarado (Mexico)",
  "🇲🇽 Alexis Vega (Mexico)",
  "🇿🇦 Percy Tau (South Africa)",
  "🇿🇦 Lyle Foster (South Africa)",
  "🇿🇦 Evidence Makgopa (South Africa)",
  "🇿🇦 Themba Zwane (South Africa)",
  "🇿🇦 Zakhele Lepasa (South Africa)",
  "🇿🇦 Iqraam Rayners (South Africa)",
  "🇿🇦 Oswin Appollis (South Africa)",
  "🇿🇦 Teboho Mokoena (South Africa)",
  "🇰🇷 Son Heung-min (South Korea)",
  "🇰🇷 Hwang Hee-chan (South Korea)",
  "🇰🇷 Lee Kang-in (South Korea)",
  "🇰🇷 Cho Gue-sung (South Korea)",
  "🇰🇷 Oh Hyeon-gyu (South Korea)",
  "🇰🇷 Hwang Ui-jo (South Korea)",
  "🇰🇷 Jeong Woo-yeong (South Korea)",
  "🇰🇷 Hong Hyun-seok (South Korea)",
  "🇨🇿 Patrik Schick (Czechia)",
  "🇨🇿 Adam Hložek (Czechia)",
  "🇨🇿 Tomáš Čvančara (Czechia)",
  "🇨🇿 Mojmír Chytil (Czechia)",
  "🇨🇿 Václav Černý (Czechia)",
  "🇨🇿 Lukáš Provod (Czechia)",
  "🇨🇿 Jan Kuchta (Czechia)",
  "🇨🇿 Antonín Barák (Czechia)",
  "🇨🇦 Jonathan David (Canada)",
  "🇨🇦 Alphonso Davies (Canada)",
  "🇨🇦 Cyle Larin (Canada)",
  "🇨🇦 Tajon Buchanan (Canada)",
  "🇨🇦 Jacob Shaffelburg (Canada)",
  "🇨🇦 Ismaël Koné (Canada)",
  "🇨🇦 Jonathan Osorio (Canada)",
  "🇨🇦 Liam Millar (Canada)",
  "🇧🇦 Edin Džeko (Bosnia and Herzegovina)",
  "🇧🇦 Ermedin Demirović (Bosnia and Herzegovina)",
  "🇧🇦 Haris Tabaković (Bosnia and Herzegovina)",
  "🇧🇦 Smail Prevljak (Bosnia and Herzegovina)",
  "🇧🇦 Benjamin Tahirović (Bosnia and Herzegovina)",
  "🇧🇦 Amar Dedić (Bosnia and Herzegovina)",
  "🇧🇦 Rade Krunić (Bosnia and Herzegovina)",
  "🇧🇦 Denis Huseinbašić (Bosnia and Herzegovina)",
  "🇶🇦 Akram Afif (Qatar)",
  "🇶🇦 Almoez Ali (Qatar)",
  "🇶🇦 Hassan Al-Haydos (Qatar)",
  "🇶🇦 Mohammed Muntari (Qatar)",
  "🇶🇦 Ahmed Alaaeldin (Qatar)",
  "🇶🇦 Yusuf Abdurisag (Qatar)",
  "🇶🇦 Assim Madibo (Qatar)",
  "🇶🇦 Abdulaziz Hatem (Qatar)",
  "🇨🇭 Breel Embolo (Switzerland)",
  "🇨🇭 Noah Okafor (Switzerland)",
  "🇨🇭 Zeki Amdouni (Switzerland)",
  "🇨🇭 Xherdan Shaqiri (Switzerland)",
  "🇨🇭 Ruben Vargas (Switzerland)",
  "🇨🇭 Dan Ndoye (Switzerland)",
  "🇨🇭 Renato Steffen (Switzerland)",
  "🇨🇭 Granit Xhaka (Switzerland)",
  "🇧🇷 Vinícius Jr (Brazil)",
  "🇧🇷 Rodrygo (Brazil)",
  "🇧🇷 Endrick (Brazil)",
  "🇧🇷 Raphinha (Brazil)",
  "🇧🇷 Gabriel Martinelli (Brazil)",
  "🇧🇷 Richarlison (Brazil)",
  "🇧🇷 Gabriel Jesus (Brazil)",
  "🇧🇷 Neymar (Brazil)",
  "🇧🇷 Lucas Paquetá (Brazil)",
  "🇧🇷 Bruno Guimarães (Brazil)",
  "🇭🇹 Duckens Nazon (Haiti)",
  "🇭🇹 Frantzdy Pierrot (Haiti)",
  "🇭🇹 Fafà Picault (Haiti)",
  "🇭🇹 Carnejy Antoine (Haiti)",
  "🇭🇹 Leverton Pierre (Haiti)",
  "🇭🇹 Derrick Etienne Jr (Haiti)",
  "🇭🇹 Danley Jean Jacques (Haiti)",
  "🇭🇹 Louicius Don Deedson (Haiti)",
  "🇲🇦 Youssef En-Nesyri (Morocco)",
  "🇲🇦 Achraf Hakimi (Morocco)",
  "🇲🇦 Hakim Ziyech (Morocco)",
  "🇲🇦 Sofiane Boufal (Morocco)",
  "🇲🇦 Amine Adli (Morocco)",
  "🇲🇦 Ayoub El Kaabi (Morocco)",
  "🇲🇦 Brahim Díaz (Morocco)",
  "🇲🇦 Soufiane Rahimi (Morocco)",
  "🇲🇦 Azzedine Ounahi (Morocco)",
  "🏴 Scott McTominay (Scotland)",
  "🏴 Che Adams (Scotland)",
  "🏴 Lyndon Dykes (Scotland)",
  "🏴 John McGinn (Scotland)",
  "🏴 Ryan Christie (Scotland)",
  "🏴 Lawrence Shankland (Scotland)",
  "🏴 Ben Doak (Scotland)",
  "🏴 Billy Gilmour (Scotland)",
  "🇺🇸 Christian Pulisic (United States)",
  "🇺🇸 Folarin Balogun (United States)",
  "🇺🇸 Timothy Weah (United States)",
  "🇺🇸 Giovanni Reyna (United States)",
  "🇺🇸 Ricardo Pepi (United States)",
  "🇺🇸 Brenden Aaronson (United States)",
  "🇺🇸 Haji Wright (United States)",
  "🇺🇸 Weston McKennie (United States)",
  "🇦🇺 Mitchell Duke (Australia)",
  "🇦🇺 Craig Goodwin (Australia)",
  "🇦🇺 Mathew Leckie (Australia)",
  "🇦🇺 Riley McGree (Australia)",
  "🇦🇺 Jackson Irvine (Australia)",
  "🇦🇺 Brandon Borrello (Australia)",
  "🇦🇺 Kusini Yengi (Australia)",
  "🇦🇺 Martin Boyle (Australia)",
  "🇵🇾 Miguel Almirón (Paraguay)",
  "🇵🇾 Julio Enciso (Paraguay)",
  "🇵🇾 Ramón Sosa (Paraguay)",
  "🇵🇾 Antonio Sanabria (Paraguay)",
  "🇵🇾 Gabriel Ávalos (Paraguay)",
  "🇵🇾 Matías Rojas (Paraguay)",
  "🇵🇾 Ángel Romero (Paraguay)",
  "🇵🇾 Adam Bareiro (Paraguay)",
  "🇹🇷 Hakan Çalhanoğlu (Türkiye)",
  "🇹🇷 Arda Güler (Türkiye)",
  "🇹🇷 Kerem Aktürkoğlu (Türkiye)",
  "🇹🇷 Cenk Tosun (Türkiye)",
  "🇹🇷 Barış Alper Yılmaz (Türkiye)",
  "🇹🇷 Yunus Akgün (Türkiye)",
  "🇹🇷 İrfan Can Kahveci (Türkiye)",
  "🇹🇷 Semih Kılıçsoy (Türkiye)",
  "🇨🇼 Leandro Bacuna (Curaçao)",
  "🇨🇼 Juninho Bacuna (Curaçao)",
  "🇨🇼 Jearl Margaritha (Curaçao)",
  "🇨🇼 Rangelo Janga (Curaçao)",
  "🇨🇼 Brandley Kuwas (Curaçao)",
  "🇨🇼 Gervane Kastaneer (Curaçao)",
  "🇨🇼 Jeremy Antonisse (Curaçao)",
  "🇨🇼 Kenji Gorré (Curaçao)",
  "🇪🇨 Enner Valencia (Ecuador)",
  "🇪🇨 Moisés Caicedo (Ecuador)",
  "🇪🇨 Piero Hincapié (Ecuador)",
  "🇪🇨 Kendry Páez (Ecuador)",
  "🇪🇨 Kevin Rodríguez (Ecuador)",
  "🇪🇨 Gonzalo Plata (Ecuador)",
  "🇪🇨 Ángel Mena (Ecuador)",
  "🇪🇨 Jeremy Sarmiento (Ecuador)",
  "🇩🇪 Florian Wirtz (Germany)",
  "🇩🇪 Kai Havertz (Germany)",
  "🇩🇪 Jamal Musiala (Germany)",
  "🇩🇪 Niclas Füllkrug (Germany)",
  "🇩🇪 Serge Gnabry (Germany)",
  "🇩🇪 Leroy Sané (Germany)",
  "🇩🇪 Thomas Müller (Germany)",
  "🇩🇪 Maximilian Beier (Germany)",
  "🇩🇪 Deniz Undav (Germany)",
  "🇨🇮 Sébastien Haller (Ivory Coast)",
  "🇨🇮 Simon Adingra (Ivory Coast)",
  "🇨🇮 Nicolas Pépé (Ivory Coast)",
  "🇨🇮 Wilfried Zaha (Ivory Coast)",
  "🇨🇮 Franck Kessié (Ivory Coast)",
  "🇨🇮 Oumar Diakité (Ivory Coast)",
  "🇨🇮 Karim Konaté (Ivory Coast)",
  "🇨🇮 Jean-Philippe Krasso (Ivory Coast)",
  "🇳🇱 Cody Gakpo (Netherlands)",
  "🇳🇱 Memphis Depay (Netherlands)",
  "🇳🇱 Xavi Simons (Netherlands)",
  "🇳🇱 Donyell Malen (Netherlands)",
  "🇳🇱 Brian Brobbey (Netherlands)",
  "🇳🇱 Wout Weghorst (Netherlands)",
  "🇳🇱 Steven Bergwijn (Netherlands)",
  "🇳🇱 Tijjani Reijnders (Netherlands)",
  "🇯🇵 Takefusa Kubo (Japan)",
  "🇯🇵 Kaoru Mitoma (Japan)",
  "🇯🇵 Takumi Minamino (Japan)",
  "🇯🇵 Daichi Kamada (Japan)",
  "🇯🇵 Ritsu Doan (Japan)",
  "🇯🇵 Ayase Ueda (Japan)",
  "🇯🇵 Kyogo Furuhashi (Japan)",
  "🇯🇵 Daizen Maeda (Japan)",
  "🇯🇵 Junya Ito (Japan)",
  "🇸🇪 Alexander Isak (Sweden)",
  "🇸🇪 Viktor Gyökeres (Sweden)",
  "🇸🇪 Dejan Kulusevski (Sweden)",
  "🇸🇪 Anthony Elanga (Sweden)",
  "🇸🇪 Emil Forsberg (Sweden)",
  "🇸🇪 Jesper Karlsson (Sweden)",
  "🇸🇪 Robin Quaison (Sweden)",
  "🇸🇪 Mattias Svanberg (Sweden)",
  "🇹🇳 Youssef Msakni (Tunisia)",
  "🇹🇳 Wahbi Khazri (Tunisia)",
  "🇹🇳 Hannibal Mejbri (Tunisia)",
  "🇹🇳 Elias Achouri (Tunisia)",
  "🇹🇳 Seifeddine Jaziri (Tunisia)",
  "🇹🇳 Haythem Jouini (Tunisia)",
  "🇹🇳 Ali Abdi (Tunisia)",
  "🇹🇳 Anis Ben Slimane (Tunisia)",
  "🇧🇪 Romelu Lukaku (Belgium)",
  "🇧🇪 Kevin De Bruyne (Belgium)",
  "🇧🇪 Jérémy Doku (Belgium)",
  "🇧🇪 Leandro Trossard (Belgium)",
  "🇧🇪 Loïs Openda (Belgium)",
  "🇧🇪 Charles De Ketelaere (Belgium)",
  "🇧🇪 Dodi Lukebakio (Belgium)",
  "🇧🇪 Youri Tielemans (Belgium)",
  "🇪🇬 Mohamed Salah (Egypt)",
  "🇪🇬 Mostafa Mohamed (Egypt)",
  "🇪🇬 Omar Marmoush (Egypt)",
  "🇪🇬 Trézéguet (Egypt)",
  "🇪🇬 Zizo (Egypt)",
  "🇪🇬 Emam Ashour (Egypt)",
  "🇪🇬 Mahmoud Kahraba (Egypt)",
  "🇪🇬 Ibrahim Adel (Egypt)",
  "🇮🇷 Mehdi Taremi (Iran)",
  "🇮🇷 Sardar Azmoun (Iran)",
  "🇮🇷 Alireza Jahanbakhsh (Iran)",
  "🇮🇷 Mehdi Ghayedi (Iran)",
  "🇮🇷 Saman Ghoddos (Iran)",
  "🇮🇷 Ali Gholizadeh (Iran)",
  "🇮🇷 Mohammad Mohebi (Iran)",
  "🇮🇷 Karim Ansarifard (Iran)",
  "🇳🇿 Chris Wood (New Zealand)",
  "🇳🇿 Ben Waine (New Zealand)",
  "🇳🇿 Kosta Barbarouses (New Zealand)",
  "🇳🇿 Sarpreet Singh (New Zealand)",
  "🇳🇿 Elijah Just (New Zealand)",
  "🇳🇿 Marco Rojas (New Zealand)",
  "🇳🇿 Callum McCowatt (New Zealand)",
  "🇳🇿 Matthew Garbett (New Zealand)",
  "🇨🇻 Ryan Mendes (Cape Verde)",
  "🇨🇻 Bebé (Cape Verde)",
  "🇨🇻 Jovane Cabral (Cape Verde)",
  "🇨🇻 Garry Rodrigues (Cape Verde)",
  "🇨🇻 Djaniny (Cape Verde)",
  "🇨🇻 Willy Semedo (Cape Verde)",
  "🇨🇻 Jamiro Monteiro (Cape Verde)",
  "🇨🇻 Kevin Pina (Cape Verde)",
  "🇸🇦 Salem Al-Dawsari (Saudi Arabia)",
  "🇸🇦 Firas Al-Buraikan (Saudi Arabia)",
  "🇸🇦 Saleh Al-Shehri (Saudi Arabia)",
  "🇸🇦 Abdulrahman Ghareeb (Saudi Arabia)",
  "🇸🇦 Sami Al-Najei (Saudi Arabia)",
  "🇸🇦 Hattan Bahebri (Saudi Arabia)",
  "🇸🇦 Ayman Yahya (Saudi Arabia)",
  "🇸🇦 Mohammed Kanno (Saudi Arabia)",
  "🇪🇸 Álvaro Morata (Spain)",
  "🇪🇸 Lamine Yamal (Spain)",
  "🇪🇸 Nico Williams (Spain)",
  "🇪🇸 Dani Olmo (Spain)",
  "🇪🇸 Pedri (Spain)",
  "🇪🇸 Mikel Oyarzabal (Spain)",
  "🇪🇸 Ferran Torres (Spain)",
  "🇪🇸 Joselu (Spain)",
  "🇪🇸 Fermín López (Spain)",
  "🇺🇾 Darwin Núñez (Uruguay)",
  "🇺🇾 Federico Valverde (Uruguay)",
  "🇺🇾 Luis Suárez (Uruguay)",
  "🇺🇾 Facundo Pellistri (Uruguay)",
  "🇺🇾 Nicolás de la Cruz (Uruguay)",
  "🇺🇾 Giorgian de Arrascaeta (Uruguay)",
  "🇺🇾 Maximiliano Araújo (Uruguay)",
  "🇺🇾 Brian Rodríguez (Uruguay)",
  "🇫🇷 Kylian Mbappé (France)",
  "🇫🇷 Ousmane Dembélé (France)",
  "🇫🇷 Marcus Thuram (France)",
  "🇫🇷 Randal Kolo Muani (France)",
  "🇫🇷 Bradley Barcola (France)",
  "🇫🇷 Antoine Griezmann (France)",
  "🇫🇷 Kingsley Coman (France)",
  "🇫🇷 Christopher Nkunku (France)",
  "🇫🇷 Olivier Giroud (France)",
  "🇳🇴 Erling Haaland (Norway)",
  "🇳🇴 Martin Ødegaard (Norway)",
  "🇳🇴 Alexander Sørloth (Norway)",
  "🇳🇴 Antonio Nusa (Norway)",
  "🇳🇴 Jørgen Strand Larsen (Norway)",
  "🇳🇴 Oscar Bobb (Norway)",
  "🇳🇴 Sander Berge (Norway)",
  "🇳🇴 Kristian Thorstvedt (Norway)",
  "🇸🇳 Sadio Mané (Senegal)",
  "🇸🇳 Nicolas Jackson (Senegal)",
  "🇸🇳 Ismaïla Sarr (Senegal)",
  "🇸🇳 Habib Diallo (Senegal)",
  "🇸🇳 Boulaye Dia (Senegal)",
  "🇸🇳 Iliman Ndiaye (Senegal)",
  "🇸🇳 Krépin Diatta (Senegal)",
  "🇸🇳 Pape Matar Sarr (Senegal)",
  "🇮🇶 Aymen Hussein (Iraq)",
  "🇮🇶 Ali Al-Hamadi (Iraq)",
  "🇮🇶 Mohanad Ali (Iraq)",
  "🇮🇶 Ibrahim Bayesh (Iraq)",
  "🇮🇶 Amir Al-Ammari (Iraq)",
  "🇮🇶 Bashar Resan (Iraq)",
  "🇮🇶 Hussein Ali (Iraq)",
  "🇮🇶 Youssef Amyn (Iraq)",
  "🇦🇷 Lionel Messi (Argentina)",
  "🇦🇷 Lautaro Martínez (Argentina)",
  "🇦🇷 Julián Álvarez (Argentina)",
  "🇦🇷 Paulo Dybala (Argentina)",
  "🇦🇷 Alejandro Garnacho (Argentina)",
  "🇦🇷 Ángel Di María (Argentina)",
  "🇦🇷 Nicolás González (Argentina)",
  "🇦🇷 Giovanni Simeone (Argentina)",
  "🇦🇷 Thiago Almada (Argentina)",
  "🇩🇿 Riyad Mahrez (Algeria)",
  "🇩🇿 Amine Gouiri (Algeria)",
  "🇩🇿 Islam Slimani (Algeria)",
  "🇩🇿 Youcef Belaïli (Algeria)",
  "🇩🇿 Baghdad Bounedjah (Algeria)",
  "🇩🇿 Saïd Benrahma (Algeria)",
  "🇩🇿 Farès Chaïbi (Algeria)",
  "🇩🇿 Houssem Aouar (Algeria)",
  "🇦🇹 Marko Arnautović (Austria)",
  "🇦🇹 Michael Gregoritsch (Austria)",
  "🇦🇹 Marcel Sabitzer (Austria)",
  "🇦🇹 Christoph Baumgartner (Austria)",
  "🇦🇹 Konrad Laimer (Austria)",
  "🇦🇹 Romano Schmid (Austria)",
  "🇦🇹 Patrick Wimmer (Austria)",
  "🇦🇹 Andreas Weimann (Austria)",
  "🇯🇴 Mousa Al-Taamari (Jordan)",
  "🇯🇴 Yazan Al-Naimat (Jordan)",
  "🇯🇴 Ali Olwan (Jordan)",
  "🇯🇴 Mahmoud Al-Mardi (Jordan)",
  "🇯🇴 Nizar Al-Rashdan (Jordan)",
  "🇯🇴 Noor Al-Rawabdeh (Jordan)",
  "🇯🇴 Ibrahim Sadeh (Jordan)",
  "🇯🇴 Hamza Al-Dardour (Jordan)",
  "🇵🇹 Cristiano Ronaldo (Portugal)",
  "🇵🇹 Rafael Leão (Portugal)",
  "🇵🇹 Bruno Fernandes (Portugal)",
  "🇵🇹 Bernardo Silva (Portugal)",
  "🇵🇹 Gonçalo Ramos (Portugal)",
  "🇵🇹 João Félix (Portugal)",
  "🇵🇹 Diogo Jota (Portugal)",
  "🇵🇹 Pedro Neto (Portugal)",
  "🇵🇹 Francisco Conceição (Portugal)",
  "🇨🇩 Cédric Bakambu (DR Congo)",
  "🇨🇩 Yoane Wissa (DR Congo)",
  "🇨🇩 Silas Katompa Mvumpa (DR Congo)",
  "🇨🇩 Théo Bongonda (DR Congo)",
  "🇨🇩 Simon Banza (DR Congo)",
  "🇨🇩 Meschack Elia (DR Congo)",
  "🇨🇩 Gaël Kakuta (DR Congo)",
  "🇨🇩 Fiston Mayele (DR Congo)",
  "🇨🇴 Luis Díaz (Colombia)",
  "🇨🇴 James Rodríguez (Colombia)",
  "🇨🇴 Jhon Durán (Colombia)",
  "🇨🇴 Rafael Santos Borré (Colombia)",
  "🇨🇴 Jhon Arias (Colombia)",
  "🇨🇴 Luis Sinisterra (Colombia)",
  "🇨🇴 Juan Fernando Quintero (Colombia)",
  "🇨🇴 Miguel Borja (Colombia)",
  "🇺🇿 Eldor Shomurodov (Uzbekistan)",
  "🇺🇿 Abbosbek Fayzullaev (Uzbekistan)",
  "🇺🇿 Jaloliddin Masharipov (Uzbekistan)",
  "🇺🇿 Oston Urunov (Uzbekistan)",
  "🇺🇿 Igor Sergeev (Uzbekistan)",
  "🇺🇿 Azizbek Turgunboev (Uzbekistan)",
  "🇺🇿 Khojimat Erkinov (Uzbekistan)",
  "🇺🇿 Odiljon Hamrobekov (Uzbekistan)",
  "🏴 Harry Kane (England)",
  "🏴 Jude Bellingham (England)",
  "🏴 Bukayo Saka (England)",
  "🏴 Phil Foden (England)",
  "🏴 Cole Palmer (England)",
  "🏴 Marcus Rashford (England)",
  "🏴 Ollie Watkins (England)",
  "🏴 Ivan Toney (England)",
  "🏴 Anthony Gordon (England)",
  "🇭🇷 Andrej Kramarić (Croatia)",
  "🇭🇷 Bruno Petković (Croatia)",
  "🇭🇷 Luka Modrić (Croatia)",
  "🇭🇷 Ivan Perišić (Croatia)",
  "🇭🇷 Mario Pašalić (Croatia)",
  "🇭🇷 Lovro Majer (Croatia)",
  "🇭🇷 Ante Budimir (Croatia)",
  "🇭🇷 Martin Baturina (Croatia)",
  "🇬🇭 Mohammed Kudus (Ghana)",
  "🇬🇭 Jordan Ayew (Ghana)",
  "🇬🇭 Iñaki Williams (Ghana)",
  "🇬🇭 Antoine Semenyo (Ghana)",
  "🇬🇭 Ernest Nuamah (Ghana)",
  "🇬🇭 Kamaldeen Sulemana (Ghana)",
  "🇬🇭 Thomas Partey (Ghana)",
  "🇬🇭 André Ayew (Ghana)",
  "🇵🇦 José Fajardo (Panama)",
  "🇵🇦 Cecilio Waterman (Panama)",
  "🇵🇦 Édgar Bárcenas (Panama)",
  "🇵🇦 Ismael Díaz (Panama)",
  "🇵🇦 Yoel Bárcenas (Panama)",
  "🇵🇦 Alberto Quintero (Panama)",
  "🇵🇦 César Yanis (Panama)",
  "🇵🇦 José Luis Rodríguez (Panama)"
];
